package UserInterface.Elements.TextFields.GlobalTextFields;

import DataManager.Parameters;
import UserInterface.Elements.ElementTypes;
import UserInterface.Elements.TextFields.MyGlobalTextField;
import UserInterface.UserInterface;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import static DataManager.Parameters.SEED;

public class GlobalSeedFrame extends MyGlobalTextField {
    private final UserInterface ui;

    public GlobalSeedFrame(UserInterface ui) {
        super(ElementTypes.GLOBAL_SEED_FRAME, ui);
        this.ui = ui;

        JLabel seedLabel = new JLabel("Seed:");
        seedLabel.setBounds(960, 17, 40, 20);
        if (Parameters.darkMode) seedLabel.setForeground(Color.white);
        ui.add(seedLabel);

        if (Parameters.darkMode) setBackground(Color.black);
        if (Parameters.darkMode) setForeground(Color.white);

        addKeyListener(new MyKeyListener());
    }

    private class MyKeyListener implements KeyListener {
        @Override
        public void keyTyped(KeyEvent e) {
            //Autogenerated. Not needed
        }

        @Override
        public void keyPressed(KeyEvent e) {
            //Autogenerated. Not needed
        }

        @Override
        public void keyReleased(KeyEvent e) {
            try {
                if (GlobalSeedFrame.this.getText().length() >= 18) throw new IllegalArgumentException();
                SEED = Long.parseLong(GlobalSeedFrame.this.getText().replace(" ", ""));
                System.out.println("Current Seed: " + SEED);
            } catch (NumberFormatException ex) {
                GlobalSeedFrame.this.ui.statusCheck.setText(GlobalSeedFrame.this.ui.statusCheck.getText() + "\n[ERROR]: Seed is not a number!");
            } catch (IllegalArgumentException ex) {
                GlobalSeedFrame.this.ui.statusCheck.setText(GlobalSeedFrame.this.ui.statusCheck.getText() + "\n[ERROR]: Seed is too long! It must be at most 18 digits long!");
            }
        }
    }
}
